batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 19
model_path: Models/03_handwriting_recognition\202307160226
train_epochs: 1
train_workers: 20
vocab: F?exY0XsAzaw351CPKl-,"k26f9qrRQ(U'O)*hJLn/E;8ZIpVoct7d4Gv.H#Wy!BSNujT:bDiMmg
width: 128
