batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 19
model_path: Models/03_handwriting_recognition\202307160202
train_epochs: 1
train_workers: 20
vocab: 8/u6bPaq)kVxvliBNWpHCyIE0Z'owF(d1hYgsD#nre-:Mj"7SLt;fTXzJU*Q9K!cG5,?3.AO42Rm
width: 128
