batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 19
model_path: Models/03_handwriting_recognition\202307152226
train_epochs: 100
train_workers: 20
vocab: lZ'wNM,R(aL-B2FtrA/D)oScvHzXx78YndemWjbs9C"V!4U*6I3#JqKkgT5?:uOipGf1;QPhE.0y
width: 128
